config/routes.rb
Rails.application.routes.draw do
  
      root 'shortens#index'
      get 's/:name', to:'shortens#s'
      get 'data', to:'shortens#data'
      post 'authenticate', to: 'authentication#authenticate'
      resources :shortens do
        resources :hitlogs
      end
  namespace :api do
    namespace :v1 do
      resources :shortens  
    end
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hitlog.rb
class Hitlog < ApplicationRecord
  belongs_to :shorten
end

app/models/shorten.rb
class Shorten < ApplicationRecord
  has_many :hitlogs, dependent: :destroy
  validates :real_url, presence: true
  validates :real_url, uniqueness: { case_sensitive: false }
  validates :short_url, uniqueness: { case_sensitive: false }
  before_validation :add_url_protocol
  before_create :record_shorten

  private
    def record_shorten
      self.count = 0;
      self.short_url = ([*('A'..'Z'),*('a'..'z'),*('0'..'9')]-%w(0 1 I O)).sample(6).join
    end

  protected 
    def add_url_protocol
      unless self.real_url[/\Ahttp:\/\//] || self.real_url[/\Ahttps:\/\//]
        self.real_url = "http://#{self.real_url}"
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/api/v1/shortens_controller.rb
class Api::V1::ShortensController < ApiController
  before_action :set_shorten, only: [:show, :edit, :update, :destroy]

  def index
    @shortens = Shorten.all
    render json: @shortens
  end

  def create
    @shorten = Shorten.new(shorten_params)
      if @shorten.save
        @shorten.short_url = "#{request.base_url}/s/#{@shorten.short_url}"
        render json: @shorten, status: :created, location: @shorten
      else
        render json: @shorten.errors, status: :unprocessable_entity
      end
  end

  private
    def set_shorten
      @shorten = Shorten.find(params[:id])
    end

    def shorten_params
      params.require(:shorten).permit(:short_url, :real_url, :count)
    end
end

app/controllers/api_controller.rb
class ApiController < ActionController::API
 before_action :authenticate_request
  attr_reader :current_user

  private

  def authenticate_request
    @current_user = AuthorizeApiRequest.call(request.headers).result
    render json: { error: 'Not Authorized' }, status: 401 unless @current_user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApiController
 skip_before_action :authenticate_request

 def authenticate
   command = AuthenticateUser.call(params[:email], params[:password])

   if command.success?
     render json: { auth_token: command.result }
   else
     render json: { error: command.errors }, status: :unauthorized
   end
 end
end

app/controllers/hitlogs_controller.rb
class HitlogsController < ApplicationController
  def create
    @shorten = shorten.find(params[:id])
    @hitlog = @shorten.hitlogs.create(hitlog_params)
    redirect_to shorten_path(@shorten)
  end
 
  private
    def hitlog_params
      params.require(:hitlog).permit(:ip, :city, :country)
    end
end

app/controllers/shortens_controller.rb
class ShortensController < ApplicationController
  before_action :set_shorten, only: [:show, :edit, :update, :destroy]

  def index
    @shortens = Shorten.order(count: :DESC).limit(10)
    # @hitlogs = Hitlog.order(created_at: :DESC).limit(10)
    @hitlogs = Hitlog.select(:ip, :city, :country, :created_at, :'shortens.short_url').joins(:shorten).order(created_at: :DESC).limit(10)
  end

  def show
  end

  def data
    @shortens = Shorten.paginate page: params[:page], per_page: 10
  end

  def s
    @shorten = Shorten.find_by(short_url: params[:name])
    if @shorten
        
        @shorten.update_columns(count: @shorten.count+1)
        
        @ip = request.ip
        @city = (request.location.city) ? request.location.city : 'unknown'
        @country = (request.location.country) ? request.location.country : 'unknown'
        
        @hitlog = @shorten.hitlogs.create(:ip => @ip, :city => @city, :country => @country)

        @notice = @shorten.real_url
        redirect_to @shorten.real_url
    else
        @notice = "Sorry, Url Not Found!"
    end
  end


  def new
    @shorten = Shorten.new
  end

  def edit
  end

  def create
    @shorten = Shorten.new(shorten_params)

    respond_to do |format|
      if @shorten.save
        format.html { redirect_to @shorten, notice: 'Shorten was successfully created.' }
        format.json { render :show, status: :created, location: @shorten }
      else
        format.html { render :new }
        format.json { render json: @shorten.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @shorten.update(shorten_params)
        format.html { redirect_to @shorten, notice: 'Shorten was successfully updated.' }
        format.json { render :show, status: :ok, location: @shorten }
      else
        format.html { render :edit }
        format.json { render json: @shorten.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @shorten.destroy
    respond_to do |format|
      format.html { redirect_to shortens_url, notice: 'Shorten was successfully destroyed.' }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

  private
    def set_shorten
      @shorten = Shorten.find(params[:id])
    end

    def shorten_params
      params.require(:shorten).permit(:short_url, :real_url, :count)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def paginate(collection, params= {})
    will_paginate collection, params.merge(:renderer => RemoteLinkPaginationHelper::LinkRenderer)
  end
end

app/helpers/hitlog_helper.rb
module HitlogHelper
end

app/helpers/hitlogs_helper.rb
module HitlogsHelper
end

app/helpers/shortens_helper.rb
module ShortensHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsShortener</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shortens/_form.html.erb
<%= form_with(model: shorten, local: true) do |form| %>
  <div class="row">
    <div class="col-md-8 column-in-center">
      <% if shorten.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(shorten.errors.count, "error") %> prohibited this shorten from being saved:</h2>

          <ul>
          <% shorten.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-8 column-in-center">
      <div class="input-group">
        <%= form.text_field :real_url, id: :shorten_real_url, placeholder: "Paste a link to shorten it", :class => 'form-control' %>
        <span class="input-group-btn">
          <%= form.submit :class => 'btn btn-default sanz-btn' %>
        </span>
      </div>
    </div>
  </div>
<% end %>

app/views/shortens/data.html.erb
  <div class="row">
  <div class="col-md-10 column-in-center">
    <div class="col-md-2 pull-right">
      <%= link_to 'New Shorten', new_shorten_path, class: "btn btn-success" %>
    </div>
    <div class="text-center">
      <%= will_paginate @shortens, renderer: BootstrapPagination::Rails %>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th>Short url</th>
          <th>Real url</th>
          <th>Count</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @shortens.each_with_index do |shorten, index| %>
          <tr <%= index %2 == 1 ? "class=success" : "class=danger" %> >
            <td><%= link_to "#{request.base_url}/s/#{shorten.short_url}", "#{request.base_url}/s/#{shorten.short_url}", class: "btn btn-info", target: :_blank %></td>
            <td><%= shorten.real_url %></td>
            <td><%= shorten.count %></td>
            <td><%= link_to 'Show', shorten, class: "btn btn-success" %></td>
            <td><%= link_to 'Edit', edit_shorten_path(shorten), class: "btn btn-warning" %></td>
            <td><%= link_to 'Destroy', shorten, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, :class => 'delete_url btn btn-danger' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/shortens/destroy.js.erb
$('.delete_url').bind('ajax:success', function() {
   $(this).closest('tr').fadeOut();
   console.log($(this).val());
});

app/views/shortens/edit.html.erb
<h1>Editing Shorten</h1>

<%= render 'form', shorten: @shorten %>

<%= link_to 'Show', @shorten %> |
<%= link_to 'Back', shortens_path %>

app/views/shortens/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-10 column-in-center">
    <h1>Top 10 Shortener clicked</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-10 column-in-center">
    <div class="col-md-2 pull-right">
      <%= link_to 'New Shorten', new_shorten_path, class: "btn btn-success" %>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th>Short url</th>
          <th>Real url</th>
          <th>Count</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @shortens.each_with_index do |shorten, index| %>
          <tr <%= index %2 == 1 ? "class=success" : "class=danger" %> >
            <td><%= link_to "#{request.base_url}/s/#{shorten.short_url}", "#{request.base_url}/s/#{shorten.short_url}", class: "btn btn-info", target: :_blank %></td>
            <td><%= shorten.real_url %></td>
            <td><%= shorten.count %></td>
            <td><%= link_to 'Show', shorten, class: "btn btn-success" %></td>
            <td><%= link_to 'Edit', edit_shorten_path(shorten), class: "btn btn-warning" %></td>
            <td><%= link_to 'Destroy', shorten, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, :class => 'delete_url btn btn-danger' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-md-10 column-in-center">
    <h1>Last Clicked URL</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-10 column-in-center">
    <table class="table">
      <thead>
        <tr>
          <th>Short Url</th>
          <th>IP</th>
          <th>City</th>
          <th>Country</th>
        </tr>
      </thead>

      <tbody>
        <% @hitlogs.each_with_index do |hitlog, index| %>
          <tr <%= index %2 == 1 ? "class=success" : "class=danger" %> >
            <td><%= link_to "#{request.base_url}/s/#{hitlog.short_url}", "#{request.base_url}/s/#{hitlog.short_url}", class: "btn btn-info", target: :_blank %></td>
            <td><%= hitlog.ip %></td>
            <td><%= hitlog.city %></td>
            <td><%= hitlog.country %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/shortens/new.html.erb
<h1>New Shorten</h1>

<%= render 'form', shorten: @shorten %>

<!-- <%= link_to 'Back', shortens_path %> -->

app/views/shortens/s.html.erb
<p id="notice"><%= @notice %></p>

  <p>
    <strong>IP:</strong>
    <%= @ip %>
  </p>
  <p>
    <strong>City:</strong>
    <%= @city %>
  </p>
  <p>
    <strong>Country:</strong>
    <%= @country %>
  </p>
<% if @shorten %>
  <p>
    <strong>Short url:</strong>
    <%= @shorten.short_url %>
  </p>

  <p>
    <strong>Real url:</strong>
    <%= @shorten.real_url %>
  </p>

  <p>
    <strong>Count:</strong>
    <%= @shorten.count %>
  </p>
<% end %>

app/views/shortens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Short url:</strong>
  <%= link_to "#{request.base_url}/s/#{@shorten.short_url}", "#{request.base_url}/s/#{@shorten.short_url}", class: "btn btn-info", target: :_blank %>
</p>

<p>
  <strong>Real url:</strong>
  <%= @shorten.real_url %>
</p>

<p>
  <strong>Count:</strong>
  <%= @shorten.count %>
</p>

<div class="col-md-2">
  <%= link_to 'Back to Dashboard', root_path , class: "btn btn-warning" %>
</div>